# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1372160667);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.slowStartup.averageTime", 1053);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20130624031040");
user_pref("browser.startup.homepage_override.mstone", "24.0a1");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1372247066769");
user_pref("datareporting.policy.firstRunTime", "1372160666769");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.main", 66);
user_pref("datareporting.sessions.current.startTime", "1372160821802");
user_pref("datareporting.sessions.current.totalTime", 3);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1372160666464,\"a\":9,\"t\":43,\"c\":true,\"m\":50,\"fp\":1202,\"sr\":1174}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.0a1");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/Applications/FirefoxNightlyA.app/Contents/MacOS/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1372089574000,\"rdfTime\":1372089574000}}}]");
user_pref("extensions.lastAppVersion", "24.0a1");
user_pref("extensions.lastPlatformVersion", "24.0a1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20130624031040");
user_pref("gecko.mstone", "24.0a1");
user_pref("general.warnOnAboutConfig", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("social.activeProviders", "{\"http://127.0.0.1:5000\":1}");
user_pref("social.enabled", true);
user_pref("social.manifest.127-0.0.1:5000", "{\"name\":\"Talkilla (127.0.0.1)\",\"iconURL\":\"http://127.0.0.1:5000/img/talkilla16.png\",\"icon32URL\":\"http://127.0.0.1:5000/img/talkilla32.png\",\"icon64URL\":\"http://127.0.0.1:5000/img/talkilla64.png\",\"sidebarURL\":\"http://127.0.0.1:5000/sidebar.html\",\"workerURL\":\"http://127.0.0.1:5000/js/worker.js\",\"description\":\"Talkilla Services\",\"author\":\"Mozilla\",\"homepageURL\":\"https://wiki.mozilla.org/Talkilla\",\"origin\":\"http://127.0.0.1:5000\",\"updateDate\":1372160701701,\"installDate\":1372160701701}");
user_pref("social.provider.current", "http://127.0.0.1:5000");
user_pref("toolkit.startup.last_success", 1372160821);
user_pref("toolkit.telemetry.previousBuildID", "20130624031040");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1374752669);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
